name: weapons_carrying_training
description: تطبيق عربي تدريبي للسلامة والحمل غير القتالي
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
flutter:
  uses-material-design: true
